import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const tools = JSON.parse(readFileSync(new URL('../src/tools.json', import.meta.url)));
const expectedCount = tools.length;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: 'light' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.env.TEST_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: '/tmp/pollob-tools-desktop.png', fullPage: false });
assert.equal(await page.locator('.tool-card').count(), expectedCount);
assert.equal(await page.locator('#web-grid .tool-card').count(), tools.filter(t => t.type === 'online').length);
assert.equal(await page.locator('#install-grid .tool-card').count(), tools.filter(t => t.type === 'install').length);
await page.keyboard.press('/');
assert.equal(await page.locator('#search').evaluate(el => el === document.activeElement), true);
await page.locator('#search').fill('COLOR shades');
assert.equal(await page.locator('.tool-card').count(), 1);
assert.equal(await page.locator('.tool-card h2').innerText(), 'Color Shade Generator');
await page.keyboard.press('Escape');
assert.equal(await page.locator('.tool-card').count(), expectedCount);
await page.locator('#search').fill('nonexistent-tool');
assert.equal(await page.locator('.tool-card').count(), 0);
assert.equal(await page.locator('#empty-state').isVisible(), true);
await page.locator('#reset-search').click();
assert.equal(await page.locator('.tool-card').count(), expectedCount);
for (const width of [375, 768, 1440, 1920]) {
  await page.setViewportSize({ width, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Overflow at ${width}`);
}
await page.setViewportSize({ width: 375, height: 900 });
await page.screenshot({ path: '/tmp/pollob-tools-mobile.png', fullPage: false });
await page.locator('footer').scrollIntoViewIfNeeded();
await page.evaluate(async () => { await Promise.all([...document.images].map(image => image.decode())); });
assert.equal(await page.locator('img').evaluateAll(images => images.every(image => image.naturalWidth > 0)), true);
assert.deepEqual(errors, []);
// Theme behavior: system preference, manual choice, persistence, and blocked storage.
await page.setViewportSize({ width: 1440, height: 1100 });
await page.evaluate(() => window.scrollTo(0, 0));
assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
await page.emulateMedia({ colorScheme: 'dark' });
await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
await page.getByRole('button', { name: 'Switch to light theme' }).click();
await page.reload({ waitUntil: 'networkidle' });
assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
await page.getByRole('button', { name: 'Switch to dark theme' }).click();
await page.reload({ waitUntil: 'networkidle' });
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(7, 19, 17)');
await page.screenshot({ path: '/tmp/pollob-tools-dark.png' });
await page.setViewportSize({ width: 375, height: 900 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.screenshot({ path: '/tmp/pollob-tools-dark-mobile.png' });
const restricted = await browser.newPage({ colorScheme: 'dark' });
await restricted.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage unavailable'); } }));
await restricted.goto(process.env.TEST_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
assert.equal(await restricted.locator('html').getAttribute('data-theme'), 'dark');
await restricted.getByRole('button', { name: 'Switch to light theme' }).click();
assert.equal(await restricted.locator('html').getAttribute('data-theme'), 'light');
await restricted.close();
assert.deepEqual(errors, []);
console.log('Theme checks passed: system preference, toggle, reload persistence, dark mobile layout, and blocked storage.');
console.log('Browser checks passed: gallery, live search, keyboard, filters, empty state, images, and four responsive widths.');
await browser.close();
