import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const tools = JSON.parse(readFileSync(new URL('../src/tools.json', import.meta.url)));
const expectedCount = tools.length;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, colorScheme: 'light' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(process.env.TEST_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: '/tmp/pollob-tools-desktop.png', fullPage: false });
assert.equal(await page.locator('.tool-card').count(), expectedCount);
assert.equal(await page.locator('#web-grid .tool-card').count(), tools.filter(t => t.type === 'online').length);
assert.equal(await page.locator('#install-grid .tool-card').count(), tools.filter(t => t.type === 'install').length);
await page.keyboard.press('/');
assert.equal(await page.locator('#search').evaluate(el => el === document.activeElement), true);
await page.locator('#search').fill('COLOR shades');
assert.equal(await page.locator('.tool-card').count(), 1);
assert.equal(await page.locator('.tool-card h2').innerText(), 'Color Shade Generator');
await page.keyboard.press('Escape');
assert.equal(await page.locator('.tool-card').count(), expectedCount);
await page.locator('#search').fill('nonexistent-tool');
assert.equal(await page.locator('.tool-card').count(), 0);
assert.equal(await page.locator('#empty-state').isVisible(), true);
await page.locator('#reset-search').click();
assert.equal(await page.locator('.tool-card').count(), expectedCount);
// Apps launcher: waffle toggle between logo and brand text, grid of tool boxes in homepage order, dismiss.
assert.equal(await page.locator('.site-header .brand #launcher-toggle').count(), 1);
const launcher = page.locator('#launcher');
assert.equal(await launcher.isHidden(), true);
await page.getByRole('button', { name: 'Browse all tools' }).click();
assert.equal(await launcher.isVisible(), true);
assert.equal(await page.locator('#launcher-toggle').getAttribute('aria-expanded'), 'true');
assert.equal(await launcher.locator('.launcher-box').count(), expectedCount);
assert.equal(await page.locator('#launcher-count').innerText(), String(expectedCount));
const byPriority = (a, b) => a.priority - b.priority;
const homepageOrder = [...tools.filter(t => t.type === 'online').sort(byPriority), ...tools.filter(t => t.type === 'install').sort(byPriority)];
assert.equal(await launcher.locator('.launcher-box').first().innerText(), homepageOrder[0].title);
assert.equal(await launcher.locator('.launcher-box').last().innerText(), homepageOrder[homepageOrder.length - 1].title);
await page.keyboard.press('Escape');
assert.equal(await launcher.isHidden(), true);
assert.equal(await page.locator('#launcher-toggle').evaluate(el => el === document.activeElement), true);
await page.getByRole('button', { name: 'Browse all tools' }).click();
assert.equal(await launcher.isVisible(), true);
await page.locator('#launcher-backdrop').click();
assert.equal(await launcher.isHidden(), true);
// Hover behavior: opens on toggle hover (no click), closes when mouse leaves the panel.
await page.locator('#launcher-toggle').hover();
await page.waitForFunction(() => !document.querySelector('#launcher').hidden);
assert.equal(await launcher.isVisible(), true);
assert.equal(await page.locator('#launcher-toggle').getAttribute('aria-expanded'), 'true');
await launcher.locator('.launcher-box').first().hover();
assert.equal(await launcher.isVisible(), true);
await page.mouse.move(720, 1000);
await page.waitForFunction(() => document.querySelector('#launcher').hidden);
assert.equal(await launcher.isHidden(), true);
assert.equal(await page.locator('#launcher-toggle').getAttribute('aria-expanded'), 'false');
// Hovering the toggle then moving away without entering the panel also closes.
await page.locator('#launcher-toggle').hover();
await page.waitForFunction(() => !document.querySelector('#launcher').hidden);
await page.mouse.move(720, 1000);
await page.waitForFunction(() => document.querySelector('#launcher').hidden);
assert.equal(await launcher.isHidden(), true);
// Gap transit: pausing between the toggle and the panel keeps the menu open.
await page.locator('#launcher-toggle').hover();
await page.waitForFunction(() => !document.querySelector('#launcher').hidden);
const gapPoint = await page.locator('#launcher-toggle').evaluate(el => {
  const rect = el.getBoundingClientRect();
  return { x: rect.left + rect.width / 2, y: rect.bottom + 12 };
});
await page.mouse.move(gapPoint.x, gapPoint.y);
await page.waitForTimeout(400);
assert.equal(await launcher.isVisible(), true);
await launcher.locator('.launcher-box').first().hover();
assert.equal(await launcher.isVisible(), true);
await page.mouse.move(720, 1000);
await page.waitForFunction(() => document.querySelector('#launcher').hidden);
// Launcher polish: all tiles fit without scrolling on desktop, count uses the
// shared pill style, and opening plays a subtle rise animation.
await page.locator('#launcher-toggle').hover();
await page.waitForFunction(() => !document.querySelector('#launcher').hidden);
assert.equal(await page.locator('#launcher-grid').evaluate(el => el.scrollHeight <= el.clientHeight + 1), true);
assert.equal(await page.locator('#launcher').evaluate(el => el.classList.contains('has-more')), false);
assert.equal(await page.locator('#launcher-count').evaluate(el => el.classList.contains('category-count')), true);
assert.equal(await page.locator('#launcher').evaluate(el => getComputedStyle(el).animationName), 'launcher-in');
await page.mouse.move(720, 1000);
await page.waitForFunction(() => document.querySelector('#launcher').hidden);
// Short viewport: the grid scrolls and a fade cue shows until scrolled to bottom.
await page.setViewportSize({ width: 1440, height: 500 });
await page.locator('#launcher-toggle').hover();
await page.waitForFunction(() => !document.querySelector('#launcher').hidden);
assert.equal(await page.locator('#launcher').evaluate(el => el.classList.contains('has-more')), true);
await page.locator('#launcher-grid').evaluate(el => { el.scrollTop = el.scrollHeight; });
await page.waitForFunction(() => !document.querySelector('#launcher').classList.contains('has-more'));
await page.mouse.move(720, 450);
await page.waitForFunction(() => document.querySelector('#launcher').hidden);
await page.setViewportSize({ width: 1440, height: 1100 });
for (const width of [375, 768, 1440, 1920]) {
  await page.setViewportSize({ width, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Overflow at ${width}`);
}
await page.setViewportSize({ width: 375, height: 900 });
await page.screenshot({ path: '/tmp/pollob-tools-mobile.png', fullPage: false });
await page.locator('footer').scrollIntoViewIfNeeded();
await page.evaluate(async () => { await Promise.all([...document.images].map(image => image.decode())); });
assert.equal(await page.locator('img').evaluateAll(images => images.every(image => image.naturalWidth > 0)), true);
assert.deepEqual(errors, []);
// Theme behavior: system preference, manual choice, persistence, and blocked storage.
await page.setViewportSize({ width: 1440, height: 1100 });
await page.evaluate(() => window.scrollTo(0, 0));
assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
await page.emulateMedia({ colorScheme: 'dark' });
await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
await page.getByRole('button', { name: 'Switch to light theme' }).click();
await page.reload({ waitUntil: 'networkidle' });
assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
await page.getByRole('button', { name: 'Switch to dark theme' }).click();
await page.reload({ waitUntil: 'networkidle' });
assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
assert.equal(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(7, 19, 17)');
await page.screenshot({ path: '/tmp/pollob-tools-dark.png' });
await page.setViewportSize({ width: 375, height: 900 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.screenshot({ path: '/tmp/pollob-tools-dark-mobile.png' });
const restricted = await browser.newPage({ colorScheme: 'dark' });
await restricted.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('Storage unavailable'); } }));
await restricted.goto(process.env.TEST_URL || 'http://localhost:5173/', { waitUntil: 'networkidle' });
assert.equal(await restricted.locator('html').getAttribute('data-theme'), 'dark');
await restricted.getByRole('button', { name: 'Switch to light theme' }).click();
assert.equal(await restricted.locator('html').getAttribute('data-theme'), 'light');
await restricted.close();
assert.deepEqual(errors, []);
console.log('Theme checks passed: system preference, toggle, reload persistence, dark mobile layout, and blocked storage.');
console.log('Browser checks passed: gallery, live search, keyboard, filters, empty state, images, and four responsive widths.');
await browser.close();
